pipeline {
    agent any
    options {
        skipStagesAfterUnstable()
    }
     tools {
    jdk 'jdk-17'
    maven 'maven-3.9'
  }
    stages {
        stage('Build') {
            steps {
                //sh 'mvn -B -DskipTests clean package'
                sh 'mvn -Denforcer.skip=true -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                sh 'mvn test'
            }
            post {
                always {
                    junit 'target/surefire-reports/*.xml'
                }
            }
        }
        stage('Deliver') { 
            steps {
                sh './jenkins/scripts/deliver.sh' 
            }
        }
    }
}
